$NetBSD$

--- wezterm-ssh/Cargo.toml.orig	2022-04-08 19:15:18.000000000 +0200
+++ wezterm-ssh/Cargo.toml	2022-05-03 12:57:05.936066617 +0200
@@ -29,8 +29,8 @@
 portable-pty = { version="0.7", path = "../pty" }
 regex = "1"
 smol = "1.2"
-ssh2 = {version="0.9.3", features=["openssl-on-win32"], optional = true}
-libssh-rs = {version="0.1.4", features=["vendored"], git="https://github.com/wez/libssh-rs.git", optional = true}
+ssh2 = {version="0.9.3", optional = true}
+libssh-rs = {version="0.1.4", features=["vendored"], optional = true}
 #libssh-rs = {path="../../libssh-rs/libssh-rs", features=["vendored"], optional = true}
 thiserror = "1.0"
 
