$NetBSD$

--- window/Cargo.toml.orig	2022-05-03 12:37:09.528382570 +0200
+++ window/Cargo.toml	2022-05-03 12:37:56.641340880 +0200
@@ -69,7 +69,7 @@
 x11 = {version ="2.18", features = ["xlib_xcb"]}
 xcb = {version="0.9", features=["render", "randr", "xkb", "xlib_xcb"]}
 xcb-util = { features = [ "cursor", "image", "icccm", "ewmh", "keysyms"], version = "0.3" }
-xkbcommon = { version = "0.5", features = ["x11", "wayland"], git="https://github.com/wez/xkbcommon-rs.git", rev="5cc8f233ac2b8bfa0d7a26fd981b77e68c3f2219"}
+xkbcommon = { version = "0.5", features = ["x11", "wayland"] }
 #xkbcommon = { version = "0.5", features = ["x11", "wayland"], path="../../xkbcommon-rs" }
 mio = "0.6"
 libc = "0.2"
