$NetBSD$

Let pkgsrc provide git snapshot of deadpool.

--- Cargo.toml.orig	2021-04-28 22:17:28.000000000 +0000
+++ Cargo.toml
@@ -30,7 +30,7 @@ config = "0.10"
 # Pin to 0.5 for now, to keep it under tokio 0.2 (issue977).
 # Fix for #803 (deadpool#92) points to our fork for now
 #deadpool = "0.5"  # pin to 0.5
-deadpool = { git = "https://github.com/mozilla-services/deadpool", branch = "deadpool-v0.5.2-issue92" }
+deadpool = { path = "../deadpool" }
 diesel = { version = "1.4", features = ["mysql", "r2d2"] }
 diesel_logger = "0.1.1"
 diesel_migrations = { version = "1.4.0", features = ["mysql"] }
