$NetBSD$

--- taplo-lsp/Cargo.toml.orig	2021-09-28 18:57:16.000000000 +0000
+++ taplo-lsp/Cargo.toml
@@ -57,7 +57,7 @@ tokio = { version = "1", features = [
     "time",
     "process",
 ] }
-clap = "3.0.0-beta.2"
+clap = "=3.0.0-beta.2"
 ctrlc = "3"
 notify = "4"
 
